# Generated by Django 5.0.6 on 2024-07-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('doble', models.CharField(max_length=40)),
                ('simple', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Noches',
        ),
        migrations.AlterModelOptions(
            name='pasajero',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.RemoveField(
            model_name='pais_destino',
            name='profesion',
        ),
        migrations.AddField(
            model_name='hotel',
            name='numeroNoches',
            field=models.IntegerField(default=1),
        ),
    ]
