# Generated by Django 5.0.6 on 2024-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_hotel_numeronoches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='numeroNoches',
            field=models.IntegerField(default=1),
        ),
    ]
